[ci]
runtime = "nix"
runner = "ubuntu-24.04"
workspace = true
with_audit = true
with_deny = true
platform = "github"
provider = "actions"

[ci.pages]
repo = "caniko/bootswain"
canonical_domain = "bootswain.tartanoglu.com"
