[package]
name = "bootswain-flash"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
readme = "../../README.md"

[dependencies]
anyhow.workspace = true
bootswain-core = { path = "../bootswain-core" }
hex.workspace = true
sha2.workspace = true
zstd.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true

